name: farm_flow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ Firebase core (latest stable)
  firebase_core: ^3.6.0

  # ✅ Firebase authentication
  firebase_auth: ^5.3.1

  # ✅ Google Sign-In
  google_sign_in: ^6.2.1

  # ✅ Facebook login
  flutter_facebook_auth: ^7.1.0

  # ✅ Geolocator (location)
  geolocator: ^12.0.0

  # ✅ Secure storage
  flutter_secure_storage: ^9.2.2

  # ✅ Shared Preferences
  shared_preferences: ^2.3.2

  # ✅ Cloud Firestore
  cloud_firestore: ^5.4.4

  # ✅ Intl (date formatting, numbers, etc.)
  intl: ^0.19.0

  # Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0   # Compatible with Dart 3.5

flutter:
  uses-material-design: true

  assets:
    - assets/background/
    - assets/farmer/
    - assets/images/
    - assets/Crops/
